[package]
name = "hyprland-autoname-workspaces"
authors = ["Cyril Levis", "Maxim Baz"]
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs.git" }
signal-hook = "0.3.14"
toml = { version = "0.5.10", features = ["indexmap", "preserve_order"] }
xdg = "2.4.1"

